const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('sop', {
  startRecording: () => ipcRenderer.invoke('recording:start'),
  stopRecording: () => ipcRenderer.invoke('recording:stop'),
  pauseRecording: () => ipcRenderer.invoke('recording:pause'),
  resumeRecording: () => ipcRenderer.invoke('recording:resume'),
  getSteps: () => ipcRenderer.invoke('steps:get'),
  updateStep: (id, title, description) => ipcRenderer.invoke('steps:update', { id, title, description }),
  deleteStep: (id) => ipcRenderer.invoke('steps:delete', { id }),
  reorderSteps: (fromIndex, toIndex) => ipcRenderer.invoke('steps:reorder', { fromIndex, toIndex }),
  addHeader: (text, afterId) => ipcRenderer.invoke('steps:addHeader', { text, afterId }),
  updateHeader: (id, text) => ipcRenderer.invoke('steps:updateHeader', { id, text }),
  addStep: (afterId) => ipcRenderer.invoke('steps:addStep', { afterId }),
  exportPdf: (title) => ipcRenderer.invoke('export:pdf', { title }),
  exportDocx: (title) => ipcRenderer.invoke('export:docx', { title }),
  exportHtml: (title) => ipcRenderer.invoke('export:html', { title }),
  importDocx: () => ipcRenderer.invoke('import:docx'),
  saveEditedImage: (stepId, dataUrl, marker) => ipcRenderer.invoke('image:save', { stepId, dataUrl, marker }),
  replaceImage: (stepId) => ipcRenderer.invoke('image:replace', { stepId }),
  removeImage: (stepId) => ipcRenderer.invoke('image:remove', { stepId }),
  listSessions: () => ipcRenderer.invoke('sessions:list'),
  listFolders: () => ipcRenderer.invoke('folders:list'),
  createFolder: (name) => ipcRenderer.invoke('folders:create', { name }),
  newSession: (title, folder) => ipcRenderer.invoke('sessions:new', { title, folder }),
  openSession: (id) => ipcRenderer.invoke('sessions:open', { id }),
  deleteSession: (id) => ipcRenderer.invoke('sessions:delete', { id }),
  setSessionFolder: (id, folder) => ipcRenderer.invoke('sessions:setFolder', { id, folder }),
  updateTitle: (title) => ipcRenderer.invoke('title:update', { title }),
  onStep: (cb) => ipcRenderer.on('recording:step', (_e, step) => cb(step)),
  onError: (cb) => ipcRenderer.on('recording:error', (_e, msg) => cb(msg)),
});
